export const downloadCSV = (expenses, filename = "arcdime-expenses.csv") => {
    if (!expenses || expenses.length === 0) {
        return false;
    }

    const headers = [
        "ID",
        "Amount",
        "Category",
        "Merchant",
        "Description",
        "Date",
        "Source",
    ];

    const rows = expenses.map((expense) => [
        expense.id,
        expense.amount,
        expense.category,
        expense.merchant || "",
        expense.description || "",
        expense.expense_date,
        expense.source_type || "manual",
    ]);

    const csvContent = [headers, ...rows]
        .map((row) =>
            row
                .map((value) => `"${String(value).replace(/"/g, '""')}"`)
                .join(",")
        )
        .join("\n");

    const blob = new Blob([csvContent], {
        type: "text/csv;charset=utf-8;",
    });

    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");
    link.href = url;
    link.download = filename;
    link.click();

    URL.revokeObjectURL(url);

    return true;
};

export const downloadMonthlyReport = (
    analytics,
    expenses,
    year,
    month,
    filename = "arcdime-monthly-report.txt"
) => {
    const monthName = new Date(year, month - 1).toLocaleString("default", {
        month: "long",
    });

    const categoryLines =
        analytics.category_breakdown?.length > 0
            ? analytics.category_breakdown
                .map(
                    (item) =>
                        `- ${item.category}: ₹${Number(item.amount).toFixed(2)}`
                )
                .join("\n")
            : "No category data available.";

    const alertLines =
        analytics.alerts?.length > 0
            ? analytics.alerts.map((alert) => `- ${alert}`).join("\n")
            : "No alerts for this month.";

    const budget = analytics.budget_status;

    const budgetSection =
        budget && budget.has_budget
            ? `
Budget Summary:
Monthly Budget: ₹${Number(budget.monthly_limit).toFixed(2)}
Spent: ₹${Number(budget.monthly_spent).toFixed(2)}
Remaining: ₹${Number(budget.monthly_remaining).toFixed(2)}
Used: ${budget.monthly_used_percentage}%
`
            : `
Budget Summary:
No budget set for this month.
`;

    const expenseLines =
        expenses.length > 0
            ? expenses
                .map(
                    (expense) =>
                        `- ${expense.expense_date} | ₹${Number(expense.amount).toFixed(
                            2
                        )} | ${expense.category} | ${expense.merchant || expense.description || "No description"
                        }`
                )
                .join("\n")
            : "No expenses recorded.";

    const report = `
ArcDime Monthly Report
${monthName} ${year}

Overview:
Total Spending: ₹${Number(analytics.total_spending).toFixed(2)}
Total Expenses: ${analytics.total_expenses}
Financial Health Score: ${analytics.financial_health_score}/100

${budgetSection}

Category Breakdown:
${categoryLines}

Alerts:
${alertLines}

Expense Entries:
${expenseLines}

Generated by ArcDime — Because Every Dime Matters.
`;

    const blob = new Blob([report.trim()], {
        type: "text/plain;charset=utf-8;",
    });

    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");
    link.href = url;
    link.download = filename;
    link.click();

    URL.revokeObjectURL(url);

    return true;
};